import { NextResponse } from 'next/server'

// In production, this would fetch from S3:
// const S3_URL = 'https://your-bucket.s3.amazonaws.com/edge-report.json'

// For now, we serve the static file from public/data
// The file is generated by: python scripts/generate_edge_report_json.py

export async function GET() {
  try {
    // Option 1: Fetch from static file (current approach)
    // In development, Next.js serves from public folder
    const baseUrl = process.env.VERCEL_URL
      ? `https://${process.env.VERCEL_URL}`
      : 'http://localhost:3000'

    const response = await fetch(`${baseUrl}/data/edge-report.json`, {
      next: { revalidate: 300 }, // Cache for 5 minutes
    })

    if (!response.ok) {
      throw new Error(`Failed to fetch edge report: ${response.status}`)
    }

    const data = await response.json()

    return NextResponse.json(data, {
      headers: {
        'Cache-Control': 'public, s-maxage=300, stale-while-revalidate=600',
      },
    })

    // Option 2: Fetch from S3 (future)
    // const s3Response = await fetch(S3_URL, { next: { revalidate: 300 } })
    // const data = await s3Response.json()
    // return NextResponse.json(data)

  } catch (error) {
    console.error('Edge report API error:', error)

    // Return fallback mock data if real data unavailable
    return NextResponse.json(
      {
        meta: {
          generated_at: new Date().toISOString(),
          gameweek: 17,
          gameweek_id: 'gw17',
          deadline: '2025-12-20T11:00:00Z',
          league: 'epl',
          data_source: 'Mock data - real data unavailable',
          error: String(error),
        },
        captain_picks: [],
        clean_sheets: [],
        buzz_alerts: [],
        errors: ['Data temporarily unavailable'],
      },
      { status: 503 }
    )
  }
}
